#! /usr/bin/env tclsh

source util.tcl
source mpd_proto.tcl

log "mprand starting..." 1

set host localhost
set port 6600

set protoversion [connect $host $port]

if [string is false $protoversion]\
{
	log "error: could not connect"
}

log "connected to $host port $port; mpd proto version $protoversion" 1

#log [consume] 1

player_status statarr
set init_consume 1
if !$statarr(consume)\
{
	# remember to turn consume mode back off
	set init_consume 0
}

consume 1
clq

rnd_song songinfo
enq_song $songinfo(file)
play

while true\
{
	set changes [idle_wait]

	# perhaps we have moved on to the next song or stopped
	if [lsearch $changes player]\
	{
		player_status statarr

		# if we're on the last song...
		if {$statarr(playlistlength) == $statarr(song) + 1}\
		{
			rnd_song songinfo
			enq_song $songinfo(file)
		}

		# if another client stopped playback...
		if {$statarr(state) == "stop"}\
		{
			log "mprand: playback stopped, terminating"
			break
		}
	}
}

if !$init_consume\
{
	# restore original setting
	consume 0
}
