#! /usr/bin/env tclsh

source util.tcl
source mpd_proto.tcl

log "starting..." 1

if {[string length [array names env MPD_HOST]] > 0} {
	set host $env(MPD_HOST)
} else {
	set host localhost
}

if {[string length [array names env MPD_PORT]] > 0} {
	set port $env(MPD_PORT)
} else {
	set port 6600
}

set protoversion [connect $host $port]

if {[string is false $protoversion]} {
	log "error: could not connect"
}

log "connected to $host port $port; mpd proto version $protoversion" 1

#log [consume] 1

set statdict [player_status]
set init_consume 1
if {![dict get $statdict consume]} {
	# remember to turn consume mode back off
	set init_consume 0
}

consume 1
clq

enq_song [dict get [rnd_song] file]
play

while {1} {
	set changes [idle_wait]

	# perhaps we have moved on to the next song or stopped
	if {[lsearch $changes player]} {
		set statdict [player_status]

		# if another client stopped playback...
		if {[dict get $statdict state] == "stop"} {
			log "playback stopped, terminating"
			break
		}

		# if we're on the last song or the playlist is empty...
		set len [dict get $statdict playlistlength]
		if {$len == 0 || $len == [dict get $statdict song] + 1} {
			enq_song [dict get [rnd_song] file]
		}
	}
}

if {!$init_consume} {
	# restore original setting
	consume 0
}
